# Generated by Django 3.1.1 on 2021-02-19 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.author')),
            ],
        ),
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('publishing_code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('ticket_number', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('telephone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_code', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_reservations', models.DateField()),
                ('date_of_return', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.book')),
                ('reader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.reader')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.publishing'),
        ),
    ]
